name: Build

on:
  push:
    branches: 
      - 'main'
    paths: 
      - 'latest_release'
  workflow_dispatch:

jobs:
  Build-arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup env
        run: |
          echo "REL=$(cat latest_release)" >> $GITHUB_ENV

      - name: Set up multiarch/qemu-user-static
        run: |
          docker run --rm --privileged multiarch/qemu-user-static:register --reset

      - uses: docker://multiarch/debian-debootstrap:arm64-buster
        with:
          args: >
            bash -c
            "apt update && apt upgrade -y && apt install curl lsb-release gnupg ca-certificates -y &&
            curl -k https://curl.se/ca/cacert.pem -o /etc/ssl/certs/ca-certificates.crt &&
            update-ca-certificates &&
            mkdir -p /etc/apt/trusted.gpg.d /etc/apt/sources.list.d &&
            curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key |  gpg --dearmor | tee /etc/apt/trusted.gpg.d/nodesource.gpg &&
            echo 'deb [signed-by=/etc/apt/trusted.gpg.d/nodesource.gpg] https://deb.nodesource.com/node_16.x buster main' >> /etc/apt/sources.list.d/nodesource.list &&
            apt update &&
            apt install make gcc g++ git ruby libarchive-tools nodejs rpm graphicsmagick icnsutils xz-utils -y &&
            rvm osx-ssl-certs update all &&
            gem install fpm --no-document &&
            npm i -g yarn &&
            cd /github/workspace &&
            git clone https://github.com/vercel/hyper.git -b v${{env.REL}} --single-branch &&
            cd ./hyper &&
            sed -e 's/      },\n      {\n        \"target\": \"snap\",\n        \"arch\": [\n          \"x64\"\n        ]//' -i electron-builder.json &&
            sed -e '/\"x64\",/d' -i electron-builder.json &&
            yarn --network-timeout 1000000 &&
            npm i app-builder-lib &&
            USE_SYSTEM_FPM=true yarn run dist --arm64 &&
            mkdir -p ../pkgs &&
            mv ./dist/*.deb ../pkgs &&
            mv ./dist/*.rpm ../pkgs &&
            mv ./dist/*.pacman ../pkgs &&
            mv ./dist/*.tar.gz ../pkgs &&
            rm -rf hyper"
            
      - name: Upload
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "pkgs/*"
          body: "# v${{env.REL}} \nRefer https://github.com/vercel/hyper/releases/tag/v${{env.REL}} \narmv7l builds use electron 17.0.0"
          name: v${{env.REL}}
          tag: v${{env.REL}}

  Build-armhf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup env
        run: |
          echo "REL=$(cat latest_release)" >> $GITHUB_ENV

      - name: Set up multiarch/qemu-user-static
        run: |
          docker run --rm --privileged multiarch/qemu-user-static:register --reset

      - uses: docker://multiarch/debian-debootstrap:armhf-buster
        with:
          args: >
            bash -c
            "apt update && apt upgrade -y && apt install curl lsb-release gnupg ca-certificates -y &&
            curl -k https://curl.se/ca/cacert.pem -o /etc/ssl/certs/ca-certificates.crt &&
            update-ca-certificates &&
            mkdir -p /etc/apt/trusted.gpg.d /etc/apt/sources.list.d &&
            curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key |  gpg --dearmor | tee /etc/apt/trusted.gpg.d/nodesource.gpg &&
            echo 'deb [signed-by=/etc/apt/trusted.gpg.d/nodesource.gpg] https://deb.nodesource.com/node_16.x buster main' >> /etc/apt/sources.list.d/nodesource.list &&
            apt install make gcc g++ git ruby libarchive-tools nodejs rpm graphicsmagick icnsutils xz-utils -y &&
            rvm osx-ssl-certs update all &&
            gem install fpm --no-document &&
            npm i -g yarn &&
            cd /github/workspace &&
            git clone https://github.com/vercel/hyper.git -b v${{env.REL}} --single-branch &&
            cd ./hyper &&
            sed -e '/\"electron\":/c\    \"electron\" : \"^17.0.0\",' -i package.json &&
            sed -e 's/      },\n      {\n        \"target\": \"snap\",\n        \"arch\": [\n          \"x64\"\n        ]//' -i electron-builder.json &&
            sed -e '/\"x64\",/d' -i electron-builder.json &&
            sed -e 's/\"arm64\"/\"armv7l\"/3' -i electron-builder.json &&
            yarn --network-timeout 1000000 &&
            npm i app-builder-lib &&
            USE_SYSTEM_FPM=true yarn run dist --armv7l &&
            mkdir -p ../pkgs &&
            mv ./dist/*.deb ../pkgs &&
            mv ./dist/*.rpm ../pkgs &&
            mv ./dist/*.pacman ../pkgs &&
            mv ./dist/*.tar.gz ../pkgs &&
            rm -rf hyper"
            
      - name: Upload
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "pkgs/*"
          body: "# v${{env.REL}} \nRefer https://github.com/vercel/hyper/releases/tag/v${{env.REL}} \narmv7l builds use electron 17.0.0"
          name: ${{env.REL}}
          tag: v${{env.REL}}
